### ISSUE TITLE
[Bug] [Linux] web text not appearing

### ISSUE THREAD

**Issue by AntoninLoubiere** [ThaaoBlues/CopyPasta#6]
The programs print in the logs the text receive but don't shows up in the UI, may be related to error in the navigator: 
```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```
or an error in the logs: 
```
Exception in thread Thread-2:
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/flaskwebgui.py", line 205, in open_browser
    self.BROWSER_PROCESS = sps.Popen(options,
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1694, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ThaaoBlues** [comment]
I don't have any idea, i will test some things on a Linux machine but I don't guarantee the full support. Thanks for the bug report !

**Comment by ThaaoBlues** [comment]
It shouldn't exist anymore since we use the default web browser now, I close the issue.
